### ISSUE TITLE
HLDS upstream bug breaks hldm tag

### ISSUE THREAD

**Issue by FlitPix** [GameServerManagers/docker-gameserver#37]
When initializing a container with the `hldm` tag, SteamCMD raises this error when installing HLDS, and the container hangs:

```
Error! App '90' state is 0xE after update job.
```

This is an upstream bug with HLDS according to the [Valve Software developer wiki](https://developer.valvesoftware.com/wiki/SteamCMD#Downloading_an_App), which I was able to successfully replicate in a fresh SteamCMD container:

> **Bug:** HLDS (appid 90) currently requires multiple runs of the app_update command before all the required files are successfully installed. Simply run app_update 90 validate multiple times until no more updates take place.

Until Valve updates HLDS to fix this bug, the above suggestion should be implemented as a temporary fix.

**Comment by dgibbs64** [comment]
LinuxGSM has fixes in place to help remove this issue. However it still might not be perfect
