### ISSUE TITLE
Where to find backup command script

### ISSUE THREAD

**Issue by Antergosgeek** [GameServerManagers/docker-gameserver#72]
Hello,

Where is the command_backup.sh located inside the container? My ts3server docker container says that it can not find ```pigz``` and the tar backup command fails with ```Broken Pipe```, I would like to remove the pigz compression from the script but need to find it first.
I can not easily install pigz on my system since I am running on a NAS.

**Comment by MicLieg** [comment]
Unfortunately I don't know much about LinuxGSM's docker container, but I was the one who added `pigz` in this [pull request](https://github.com/GameServerManagers/LinuxGSM/pull/4509).

You can take a look [here](https://github.com/GameServerManagers/LinuxGSM/pull/4509/files#diff-3b4b51bd02b18d3cf05d722443d2dc0d1a87a27ded78e886958dd787bac5e5f5) to see what I changed exactly.

**Comment by Antergosgeek** [comment]
Thank you, so basically the script is located at ```lgsm/modules/command_backup.sh``` and I could just revert that to the normal tar command without ```pigz``` and make that persistent. Let me check and I‘ll report back.

**Comment by Antergosgeek** [comment]
> Unfortunately I don't know much about LinuxGSM's docker container, but I was the one who added `pigz` in this [pull request](https://github.com/GameServerManagers/LinuxGSM/pull/4509).
> 
> You can take a look [here](https://github.com/GameServerManagers/LinuxGSM/pull/4509/files#diff-3b4b51bd02b18d3cf05d722443d2dc0d1a87a27ded78e886958dd787bac5e5f5) to see what I changed exactly.

Thank you so much!
This worked perfectly!
I copied ```/app/lgsm/modules``` to a new directory outside the container and and mounted that directory back to the container as a volume to make it a persistent. Then I changed the ```tar``` in the ```command_backup.sh``` back to what it was before without the ```pigz``` compression. I also created a persistent volume for ```/app/lgsm/backup``` now everything works perfectly on my NAS!!!
