### ISSUE TITLE
Rust: environment.sh: Couldn't find Steam root directory

### ISSUE THREAD

**Issue by d3adwolf** [GameServerManagers/docker-gameserver#73]
Cannot start the server when using Carbon.
```bash
rustserver@rust:~$ docker exec -it --user linuxgsm rustserver ./rustserver st
[ INFO ] Starting rustserver: Running Carbon environment.sh
[  OK  ] Updating rustserver: Checking for update: SteamCMD

Update available
* Local build: 14649231
* Remote build: 
* Branch: public
https://steamdb.info/app/258550/

[ START ] Updating rustserver: SteamCMD
Branch: public
/data/.local/share/Steam/steamcmd
/app
steamcmd.sh[9305]: Couldn't find Steam root directory from /data/.local/share/Steam/steamcmd/steamcmd.sh, aborting!
Complete! Updating rustserver: SteamCMD
```

**Comment by justdawee** [comment]
Hey man, did you find any solution or workaround for this error? 
I am also having an issue with this, but I'm not running the server through docker, its just a native Debian 12.

```bash
[ INFO ] Starting rustserver: Running Carbon environment.sh
[  OK  ] Updating rustserver: Checking for update: SteamCMD

Update available
* Local build: 16198637
* Remote build:
* Branch: public
https://steamdb.info/app/258550/

[ START ] Updating rustserver: SteamCMD
Branch: public
.
/home/rustserver/.steam/steamcmd
steamcmd.sh[936920]: Couldn't find Steam root directory from ./steamcmd.sh, aborting!
Complete! Updating rustserver: SteamCMD
```

**Comment by justdawee** [comment]
By the way, thanks for your reply (average russian helpfulness) 
I found the solution, the problem was that if you set the updateonstart="true" on the LGSM config file, you will get this error. Get rid of that and it should work if someone else gets this error.

**Comment by d3adwolf** [comment]
> By the way, thanks for your reply (average russian helpfulness) I found the solution, the problem was that if you set the updateonstart="true" on the LGSM config file, you will get this error. Get rid of that and it should work if someone else gets this error.

Hi, it's been a few months, I had nothing to add except to close the issue. If you now use the current Docker container LGSM and install Oxide or Carbon in it with updateonstart=“true” everything will work perfectly and without issues.
