### ISSUE TITLE
j2cli not supported on python 3.12

### ISSUE THREAD

**Issue by queria** [GameServerManagers/docker-gameserver#77]
On system with newer python 3.12 current dependency on j2cli will not work.

Seems j2cli is currently not maintained as mentioned in https://github.com/kolypto/j2cli/issues/80

Suggested there as possible alternative could be https://pypi.org/project/jinjanator/ (by its author).

---

Alternatively, if just env + template.j2 is needed, i think that directly using custom python script would be enough.

**Comment by queria** [comment]
I've opened two PRs, for both - custom script as also for switching to jinjanator - feel free to pick preferred one, or none if other approach is desired.

**Comment by dgibbs64** [comment]
Thanks. I will take a look at this
